name: Deploy Functions

on:
  push:
    branches:
      - develop
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy to Dev
        if: contains(toJSON(github.ref), 'develop')
        run: |
          zip -r functions_dev.zip ./functions -x '*python*'
          aws s3 cp ./functions_dev.zip s3://${{ secrets.AWS_S3_TERAKOYA_BUCKET_NAME }}/lambda/booking/

      - name: Deploy to Prod
        if: contains(toJSON(github.ref), 'master')
        run: |
          zip -r functions_prod.zip ./functions -x '*python*'
          aws s3 cp ./functions_prod.zip s3://${{ secrets.AWS_S3_TERAKOYA_BUCKET_NAME }}/lambda/booking/

      #TODO: Manually set a new source code deployed above in settings of each Lambda functions
      # or execute the same number of commands as Lambda Functions like below
      # aws lambda update-function-code --function-name <func_name> --s3-bucket <bucket_name> --s3-key <zip_file_path>
      # aws lambda update-function-code --function-name <func_name> --s3-bucket <bucket_name> --s3-key <zip_file_path>
      # ...
